#!/bin/bash

if [[ "$1" == "" || ! -d "$1" ]] ;
then
  echo "no folder exists, please check it."
  exit
fi

dir=$1
dirname=`basename $dir`
append=idx
action="echo \$f"
sigc="stat -c %Y"
mdir=${dir}${append}

if [ "$dir" == "$mdir" ] ;
then
  echo "something is wrong..."
  exit
fi

if [ -f "$dirname" ] ;
then
  echo "this is not a folder, weird stuff happened."
  exit
fi

for f in `find $dir -type f`;
do
  mpath=`dirname $f | sed 's/'$dirname'/'$dirname$append'/'`
  mname=`basename $f`
  fsig=`cat $mpath/$mname`
  if [ "$fsig" != "`eval "$sigc $f" | awk '{print $1}' `"  ] ;
  then
    eval $action
  fi
done
